<<<<<<< HEAD
=======
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor: TRACE
server:
    port: 8000
>>>>>>> 51bc36dd907306a4a92338269502a5a80dcf1bb7
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shopping_app?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
        password: roni95

    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB

    mvc:
        hiddenmethod:
            filter:
                enabled: true
    sql:
        init:
            mode: never
    #      should be always on first start

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect

        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true

<<<<<<< HEAD

=======
>>>>>>> 51bc36dd907306a4a92338269502a5a80dcf1bb7
    #Cloudinary Properties cloud
    #cloudinary:
    #api-key:
    #api-secret:
    #cloud-name:
<<<<<<< HEAD


logging:
    level:
        org.springframework.security: TRACE

server:
    port: 8000
=======
>>>>>>> 51bc36dd907306a4a92338269502a5a80dcf1bb7
